CREATE TABLE IF NOT EXISTS listing_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    url VARCHAR(2048) NOT NULL,
    position INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_listing_images_listing_id ON listing_images (listing_id);
