from __future__ import annotations

from typing import Protocol

from src.domain.entities import Category, Listing, Message, User


class UnitOfWorkPort(Protocol):
    def commit(self) -> None: ...

    def refresh(self, entity: object) -> None: ...


class UserRepositoryPort(Protocol):
    def add(self, entity: User) -> User: ...

    def get(self, entity_id: int) -> User | None: ...

    def list_all(self) -> list[User]: ...

    def delete(self, entity: User) -> None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def has_related_content(self, user_id: int) -> bool: ...


class CategoryRepositoryPort(Protocol):
    def add(self, entity: Category) -> Category: ...

    def get(self, entity_id: int) -> Category | None: ...

    def list_all(self) -> list[Category]: ...

    def delete(self, entity: Category) -> None: ...

    def get_by_name(self, name: str) -> Category | None: ...

    def has_related_listings(self, category_id: int) -> bool: ...


class ListingRepositoryPort(Protocol):
    def add(self, entity: Listing) -> Listing: ...

    def get(self, entity_id: int) -> Listing | None: ...

    def delete(self, entity: Listing) -> None: ...

    def list_visible(
        self,
        *,
        query: str | None = None,
        category_id: int | None = None,
        min_price: float | None = None,
        max_price: float | None = None,
        sort_by: str = "created_at",
        sort_order: str = "desc",
    ) -> list[Listing]: ...

    def list_for_moderation(self) -> list[Listing]: ...

    def list_owned(self, owner_id: int) -> list[Listing]: ...


class MessageRepositoryPort(Protocol):
    def add(self, entity: Message) -> Message: ...

    def delete(self, entity: Message) -> None: ...

    def list_for_user(self, user_id: int) -> list[Message]: ...

    def get_for_user(self, message_id: int, user_id: int) -> Message | None: ...
